pyms:
  requests:
    data: ""
  tracer:
    client: "jaeger"
    host: "jaeger"
    component_name: "Chat Svc"
ms:
  DEBUG: true
  TESTING: false
  APP_NAME: "Chat Svc"
  APPLICATION_ROOT : /
  SECRET_KEY: "gjr39dkjn344_!67#"
  service_host: http://chat-baas:8083/